### PR TITLE
[Lucid] Update badge and repository

### PR DESCRIPTION
**Pull request by clintnetwork**
Hi,

Sorry for that, I missed to change the build badge, is it good now!

And also changed the repository.

Thank you @luciusmagn

### CODE REVIEW

**Comment by palfrey** [comment]
This got fixed in #804

**Comment by clintnetwork** [comment]
Hmm @palfrey, please change Travis to GitHub Actions :D

**Comment by palfrey** [comment]
@clintnetwork Can you update this PR so it doesn't have conflicts with current master then please?

**Comment by clintnetwork** [comment]
I make a new PR!

**Pull request closed without merging**
