### PR TITLE
Move lapce from Text Editors to IDE

### PR DESCRIPTION
**Pull request by buxx**
Add Lapce pure Rust IDE

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Comment by buxx** [comment]
@Israel-Laguan Seems CI refuse it : 

    Error: ErrorMessage { msg: "Not high enough metrics (None stars < 50, and None cargo downloads < 2000): Lapce — Pure Rust IDE" }

Maybe should I link the github ? https://github.com/lapce/lapce

**Comment by Israel-Laguan** [comment]
Also add the CI pipeline for completion

**Comment by buxx** [comment]
Oh, I just seen pace was in list but in text editor section. I modified thie pull request to move it. But, I understand if you prefer close it.

**Comment by Israel-Laguan** [comment]
Please move it

**Comment by palfrey** [comment]
> Oh, I just seen pace was in list but in text editor section. I modified the pull request to move it. But, I understand if you prefer close it.

This is a [wider problem](https://github.com/rust-unofficial/awesome-rust/issues/1360) we don't have a good answer to yet, but this move is fine.

**Review by Carol25170 — COMMENTED** [review]
@palfrey @buxx

**Pull request merged**
