### PR TITLE
Add Theseus OS to Operating Systems

### PR DESCRIPTION
**Pull request by kevinaboos**
Added Theseus OS to the Operating Systems section.

Thanks for maintaining this awesome list!

### CODE REVIEW

**Comment by kevinaboos** [comment]
Hmm, it looks like the CI failure is due to the tool assuming that a redirect `301` is an actual error. Both links work, though.

**Comment by kevinaboos** [comment]
@palfrey the link check linter ought to pass now, thanks.

**Comment by palfrey** [comment]
> @palfrey the link check linter ought to pass now, thanks.

Thanks. We've had too many things that have a 301 only to later disappear, so we want to to make sure we've got the updated URL for things!

**Comment by kevinaboos** [comment]
Totally understand. Thanks!

**Pull request merged**
