### PR TITLE
Adding Sniffnet: application to monitor your network traffic

### PR DESCRIPTION
**Pull request by GyulyVGC**
[Sniffnet](https://github.com/GyulyVGC/sniffnet) is a cross-platform application to monitor Internet traffic with ease.

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
Looks good
image

Have more than 50 stars
image

**Comment by GyulyVGC** [comment]
Am I expected to correct the Rust build workflow fail? 
Can someone help me? It seems like something unrelated with my edits

**Comment by palfrey** [comment]
> Am I expected to correct the Rust build workflow fail? Can someone help me? It seems like something unrelated with my edits

Yup. The build has failed here, because some things have changed and broken `main`. I'll poke at those and get them fixed now as they block this getting merged.

**Comment by GyulyVGC** [comment]
Thanks!

**Pull request merged**
