### PR TITLE
Add third-party cargo subcommand cargo-x

### PR DESCRIPTION
**Pull request by liuchong**
I've wrote "A very simple third-party cargo subcommand to execute a custom command", which run custom commands defined in ~/.x.toml, project/x.toml or Cargo.toml's [package.metadata.x] section, like a cargo-x my-build, cargo x my-lint.

I'd like to add it into the awesome list, if it seems helpful.

### CODE REVIEW

**Comment by liuchong** [comment]
I have an example of it:
https://github.com/liuchong/bkb/blob/dcd8f0909c76e570d0f6f994756ad272f0bfdce1/bkb-srv/Cargo.toml#L7
https://github.com/liuchong/bkb/blob/dcd8f0909c76e570d0f6f994756ad272f0bfdce1/.travis.yml#L14

**Comment by luciusmagn** [comment]
Hey, this is pretty cool! Thank you for your contribution to the list

**Comment by liuchong** [comment]
Just added support for windows

**Comment by luciusmagn** [comment]
Ah, I don't particularly care for Windows, but sounds neat!

**Comment by liuchong** [comment]
Thanks！

**Comment by liuchong** [comment]
Thanks!

**Pull request merged**
