### PR TITLE
Add Voila to system-tools

### PR DESCRIPTION
**Pull request by Alonely0**
I don't know if it'll fit better in utilities

### CODE REVIEW

**Comment by palfrey** [comment]
> I don't know if it'll fit better in utilities

Looks fine in system tools. Can you please fix the markdown and sorting issues flagged by the CI?

**Comment by Alonely0** [comment]
> Can you please fix the markdown and sorting issues flagged by the CI?

I think now it's fixed

**Comment by palfrey** [comment]
> > Can you please fix the markdown and sorting issues flagged by the CI?
> 
> I think now it's fixed

Lint fix done, but it hasn't been reordered as per the Rust CI check output

**Comment by Alonely0** [comment]
Run workflows, so we can see if the ordering error is fixed

**Pull request merged**
