### PR TITLE
Add mail-auth to Email

### PR DESCRIPTION
**Pull request by mdecimus**
A library for e-mail authentication with DKIM, ARC, SPF and DMARC support. The repository just reached 50 stars. Thanks.

### CODE REVIEW

**Comment by palfrey** [comment]
This needs the build failure fixing. There's a sort issue in the logs

**Comment by mdecimus** [comment]
> This needs the build failure fixing. There's a sort issue in the logs

Should I resubmit this PR sorting the entries or is this something you'll fix before merging? Thanks.

**Comment by palfrey** [comment]
Please add a commit fixing this

**Comment by mdecimus** [comment]
Fixed!

**Pull request merged**
