### PR TITLE
Adding Lucid KV Store

### PR DESCRIPTION
**Pull request by clintnetwork**
Hi,

I've added Lucid, that it's an high performance KV Store.

Cheers!

### CODE REVIEW

**Comment by clintnetwork** [comment]
Ah the fail check hmm

**Comment by clintnetwork** [comment]
@luciusmagn do you know why ?

**Comment by luciusmagn** [comment]
@clintnetwork yeah, but it's unrelated.

Thanks a lot for your contribution to the list, I was actually looking for a Rust KV store a while ago myself!

**Comment by clintnetwork** [comment]
Oh, thank you!

You are welcome to contribute on Lucid if you want (it's an HTTP KV store for information)

**Pull request merged**
