### PR TITLE
Adding BIP39

### PR DESCRIPTION
**Pull request by clintnetwork**
Github: https://github.com/infincia/bip39-rs

### CODE REVIEW

**Comment by clintnetwork** [comment]
Fuck, I failed my second PR, feel free to add the link if you want (about bip 39 not pgp, it was my first PR #652)

**Comment by luciusmagn** [comment]
How did you fail your PR? I am not sure but it looks fine after taking a quick glance

**Comment by clintnetwork** [comment]
Yes but i have added sequoia in this PR that was added in the previous one :/ but you can merge if you want

**Comment by luciusmagn** [comment]
Ah, that's fine. Thank you for your contribution to the list!

**Pull request merged**
