### PR TITLE
Support optional use of Github secrets to workaround rate limits

### LINKED ISSUE #859: 429 errors from Github
We're seeing 429 errors when trying to request Github sites. This is because we're doing >60 requests/hour, which is the limit for unauthenticated requests. We should start optionally authenticating requests (and doing this in CI) so that we can get to the 5000 requests/hour allowed there, and probably also auto-rewrite all Github URLs to request the API instead so we can more easily use the authentication.

### PR DESCRIPTION
**Pull request by palfrey**
This would fix #859 (429 errors from Github) but I don't have enough permissions to add a new secret value to Travis.

@luciusmagn Any thoughts? Do you have enough access for this?

### CODE REVIEW

**Comment by palfrey** [comment]
@kud1ing Do you still have enough access to add a secret? Relatedly, I don't appear to be able to restart Travis builds anymore which I used to be able to :(

**Comment by kud1ing** [comment]
Hi, no i am sorry. This is bound to the organization, which i've left.

**Comment by palfrey** [comment]
@Manishearth Can you help here?

**Comment by palfrey** [comment]
I'm ok with adding my own secrets to the travis.yml, but only if they're encrypted with the standard Travis encryption stuff. I can't do that however as I don't have enough access on travis, probably because I don't have enough access on this repository. If that can be fixed, I can fix the rest of things myself.

**Comment by badboy** [comment]
We should be able to make @palfrey an admin on this repo. @Manishearth, you're good with that?

**Comment by palfrey** [comment]
@badboy @Manishearth Any further thoughts on this?

**Comment by Manishearth** [comment]
Yeah, this has been in my queue, i just have a ton of notifications to deal with.

You've been maintaining this pretty well, I'm okay with granting admin access. Please use it responsibly :smile:

**Comment by palfrey** [comment]
Cool, thanks. I've added the secrets now (in the Travis UI, not the .travis.yml)

**Pull request merged**
