### PR TITLE
Add MASQ Node

### PR DESCRIPTION
**Pull request by bertllll**
Please consider to register this project for your list. Thank you.

### CODE REVIEW

**Comment by bertllll** [comment]
@replicadse Please tell me if I did it wrong again.

**Comment by luciusmagn** [comment]
A'ight, cheers. Thank you for your contribution to the list!

**Comment by palfrey** [comment]
@bertllll Any idea what's happened to MASQ? The entire github org appears to have gone 404.

**Comment by bertllll** [comment]
We don't know yet. But we're trying to figure out. All I know is it hasn't
happened with our intention; we also consider an attack to us but now it's
still very unlikely. I think we're gonna wait what will come next and also
our leaders may take some action to defend.

The irony is that we've got listed on your list after a long waiting, so I
was about to celebrate that and now this...

Please be indulgent to us until this ugly situation clarifies.

Thanks for asking anyway

čt 12. 8. 2021 v 21:14 odesílatel Tom Parker-Shemilt <
***@***.***> napsal:

**Comment by bertllll** [comment]
I forgot to say...a few hours ago everything was fine...so it's really
devastating to see this happening...

By the way, the repo is still there, but only team members can see it.
Though some functions of GitHub doesn't work well even fro the members now.
I've never seen anything like that before, on the other hand I stay calm, I
just wanted to inform you of the situation somewhat closely.

čt 12. 8. 2021 v 21:31 odesílatel Bert ***@***.***> napsal:

**Comment by luciusmagn** [comment]
I suggest making backups of everything, just to be on the safe side. Nasty stuff

**Comment by bertllll** [comment]
I respect you guys @palfrey @luciusmagn so I want to be open in my words. Act as you want to based on the following. 

We've analyzed the situation and it all leads to yesterday when a certain story played out. 

I've been keeping an eye on your repo awhile and been hoping to get our project listed but it made me to rack my head in order to understand why I had been failing in meeting your criteria (also sometimes you did some maintanace at you and it prolonged the wainting period again) so yesterday, not anticipating that, I read a comment you left somewhere here about a new strategy of judging projects to accept them or reject. I found that you added criteria where you either have to have a certain amount of stars or a certain amount of downloads via cargo. I got horrified because, first, we don't publish on crates.io, second, at the time of reading that we had only about 20 stars at the repo and it was way not enough. I felt like we would never get listed so I mentioned to my colleagues how sad I'm and why. They thought up though that it can be fixed, with this in mind, they would ask our supporters from social media (but there really is a lot of tech-guys among them) to rate us with stars from they GitHub accounts and they didn't hessitate to do it. 
From today's perspective it may have been a mistake, but do believe that our intensions were clear, I think that our project deserves publicity and this incident pays us back too bad. I was worried that it may not be fair to do that but they convinced me by saying that there is no fraud on letting our true supporters to manifest their favour. 

By all evidences, we fell into the trap of the GitHub's spam bot which was followed by dragging our repo down from the public. I'm sorry. Can we still please take a place in your list. I always liked the idea so I hope we will.

**Comment by palfrey** [comment]
> From today's perspective it may have been a mistake, but do believe that our intensions were clear, I think that our project deserves publicity and this incident pays us back too bad. I was worried that it may not be fair to do that but they convinced me by saying that there is no fraud on letting our true supporters to manifest their favour.
> 
> By all evidences, we fell into the trap of the GitHub's spam bot which was followed by dragging our repo down from the public. I'm sorry. Can we still please take a place in your list. I always liked the idea so I hope we will.

Oh wow. Uh, sorry! I hope you can get yourselves back from being blacklisted ASAP. You have at least demonstrated _thoroughly_ the core notion behind the star filtering i.e. a metric demonstrating that your project is popular (which TBH, is really hard for me to tell for most crypto projects, as they almost always look really professional, even if all they've got is one person using it).

I'm assuming that whenever you come back you'll probably have >50 stars, and if you don't you're definitely going on the whitelist of "projects we know are popular enough" :)

**Comment by bertllll** [comment]
Thank you for your friendly attitude! @palfrey 

It might take up to a week but hopefully less to get the rights to our repo back. I can imagine that it might cause your CI to be failing, I worry a bit it's gonna be additional troubles to you.

**Comment by palfrey** [comment]
I'm going to leave it be for the moment. If this hasn't resolved in a day or two, I'll remove the entry for the moment, but happy to put it back immediately once Github restores you.

**Comment by palfrey** [comment]
https://github.com/rust-unofficial/awesome-rust/commit/e67c5cbae35fc88d8be59997deb51530ec498430 removes MASQ so we have a fixed CI. When the Github repo re-appears, you can get readded. Please comment here when that occurs.

**Comment by bertllll** [comment]
Hello @palfrey! 

May I ask you to put us back in the list? Our repository has become alive again since yesterday. Thanks for your patience with us. :)

**Comment by palfrey** [comment]
> Hello @palfrey!
> 
> May I ask you to put us back in the list? Our repository has become alive again since yesterday. Thanks for your patience with us. :)

5646ba1fb0d3e9c289f6e0d1194a629479d3135e re-adds MASQ

**Pull request merged**
