### PR TITLE
path_abs and stfu8

### PR DESCRIPTION
**Pull request by vitiral**
These are two libraries I've been working on for a fair amount of time within my `artifact` project. Their use cases are both pretty solid IMO and they should be searchable on this excellent list!

Thanks!

### CODE REVIEW

**Comment by luciusmagn** [comment]
There are redirects in your entries. The badge link is supposed to be from the api subdomain. If you fix it, I can merge, the additions looks pretty neat.

> Issues :-(
> > Links 
>  1. [L0683] 301 https://travis-ci.org/vitiral/stfu8.svg?branch=master  → https://api.travis-ci.org/vitiral/stfu8.svg?branch=master 
>  2. [L0689] 301 https://travis-ci.org/vitiral/path_abs.svg?branch=windows  → https://api.travis-ci.org/vitiral/path_abs.svg?branch=windows

**Comment by vitiral** [comment]
whoops, thanks. Should be fixed now!

**Comment by luciusmagn** [comment]
A-OK now! Merging

**Comment by vitiral** [comment]
Thanks!

**Pull request merged**
