### PR TITLE
Add ILLA Cloud to Productivity

### PR DESCRIPTION
**Pull request by JerryMaoMao**
ILLA is an open-source low-code tool that has a lot of parts written in rust. It has 4.8k stars on Github now.

### CODE REVIEW

**Comment by palfrey** [comment]
I'm not seeing any Rust work there
image

**Comment by JerryMaoMao** [comment]
You can check it here: https://github.com/illacloud/illa
We used Rust to write a part of the project.

**Comment by palfrey** [comment]
> You can check it here: https://github.com/illacloud/illa We used Rust to write a part of the project.

That's not the project you've linked to though.

**Comment by JerryMaoMao** [comment]
I can change the link to the project with rust. will that work?

**Pull request merged**
