### PR TITLE
Add warp

### PR DESCRIPTION
**Pull request by TSOTSI1**
I'd like to add popular web server framework - warp

[Github](https://github.com/seanmonstar/warp)
[crate](https://crates.io/crates/warp)
Version: 0.3.2
Total Downloads: 5,413,109

Thanks :),
TSOTS1

### CODE REVIEW

**Comment by TSOTSI1** [comment]
Hi @palfrey, 
Thank you for modifying the PR's title, and the Rust / build failing seems it thread 'main' panicked at '"{\"message\":\"API rate limit exceeded for 125.230.217.205. Any suggestion for this failure?
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by palfrey** [comment]
> Hi @palfrey, Thank you for modifying the PR's title, and the Rust / build failing seems it thread 'main' panicked at '"{"message":"API rate limit exceeded for 125.230.217.205. Any suggestion for this failure? https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

That's not the build failure. The error as shown in https://github.com/rust-unofficial/awesome-rust/runs/7122568458?check_suite_focus=true is that warp wasn't placed in alphabetical order, and the build log shows where it should be

Also, it's in the wrong section. Warp is a web server framework, and so should be under Libraries / Web Programming / HTTP Server .

**Comment by TSOTSI1** [comment]
@palfrey, Thank your for your explanation and review, I've updated it again, please feel free to check.

**Comment by palfrey** [comment]
It's in the right section, but wrong ordering. See build log

```
--- original
+++ modified
@@ -16,7 +16,7 @@
 Rustless — A REST-like API micro-framework inspired by Grape and Hyper build badge
 Salvo — an easy to use webframework base on hyper and tokio. build build
 Saphir — A progressive web framework with low-level control, without the pain.
+seanmonstar/warp — A super-easy, composable, web server framework for warp speeds. crate
 tiny-http — Low level HTTP server library build badge
 tokio/axum - Ergonomic and modular web framework built with Tokio, Tower, and Hyper Build badge
-tomaka/rouille — Web framework in Rust build badge
-seanmonstar/warp — A super-easy, composable, web server framework for warp speeds. crate
\ No newline at end of file
+tomaka/rouille — Web framework in Rust build badge
\ No newline at end of file
Error: ErrorMessage { msg: "Sorting error" }
```

**Comment by palfrey** [comment]
Closing while we wait for a response on the issues here

**Comment by TSOTSI1** [comment]
Hi @palfrey, 
sorry so late to reply, I've updated the latest commit to resolve the sort order, could you help to re-open this PR? Thanks

**Pull request merged**
