### PR TITLE
Add Network programming / Bluetooth / bluer

### PR DESCRIPTION
**Pull request by surban**
Criteria for adding:

BlueR was called BLEZ and located at https://github.com/surban/blez before it became the official Rust binding for BlueZ and moved to their GitHub organization.

Together the old and new repository have 40 + 28 = 68 stars.

### CODE REVIEW

**Comment by palfrey** [comment]
The stars aren't necessarily additive as they may well be a lot of the same people. Why wasn't the repo moved over if it was the same project? That would have preserved the existing stars.

**Comment by surban** [comment]
A move would have indeed been better, however this was not possible because it would have required some GitHub permissions in the BlueZ organization that could not be granted to me due to confidentiality agreements. I don't know further details but in the end their permission system did not allow for it so we had to transfer the repository manually.

**Comment by surban** [comment]
Reopening since crate has reached 2800+ downloads.

https://crates.io/crates/bluer

**Comment by palfrey** [comment]
> Reopening since crate has reached 2800+ downloads.
> 
> https://crates.io/crates/bluer

Excellent. Now passes that step, but there's some whitespace issues. See linting build logs.

**Comment by surban** [comment]
Fixed.

**Pull request merged**
