### PR TITLE
Add 1History

### PR DESCRIPTION
**Pull request by jiacai2050**

### CODE REVIEW

**Comment by palfrey** [comment]
Please have a look at the ordering error in the build logs

**Comment by jiacai2050** [comment]
@palfrey PTAL

**Comment by jiacai2050** [comment]
```
https://amethyst.rs/ Link { last_working: Some(2022-03-10T00:13:40.360722398+00:00), updated_at: 2022-03-17T07:14:00.734117439+00:00, working: No(ReqwestError { error: "error sending request for url (https://amethyst.rs/): error trying to connect: dns error: failed to lookup address information: Name or service not known" }) }
Error: ErrorMessage { msg: "1 urls with errors" }
Error: Process completed with exit code 1.
```
@palfrey I have no idea why this CI build...

**Comment by palfrey** [comment]
Please merge master into this branch (or enable maintainer merge on this PR) and the build should fix itself

**Comment by jiacai2050** [comment]
@palfrey PTAL

**Comment by jiacai2050** [comment]
@palfrey Thanks

**Pull request merged**
