### PR TITLE
Add Mini RPS

### PR DESCRIPTION
**Pull request by marcodpt**
Add my repository to the list.

[MiniRPS](https://github.com/marcodpt/minirps)

[crates.io](https://crates.io/crates/minirps)

Thank you very much for your attention @palfrey

### CODE REVIEW

**Comment by palfrey** [comment]
Because this project succeeds only on the crate downloads not the repo stars, you'll need to add a crates link to the description.

**Comment by marcodpt** [comment]
Fixed

**Comment by palfrey** [comment]
> Fixed @palfrey

In the README changes, not the pr. Our CI pays no attention the PR descriptions 😀

**Comment by marcodpt** [comment]
@palfrey 

Sorry for my ignorance.

See if this is what you expect, or if necessary, let me know how it should be done.

I apologize for the inconvenience.

**Pull request merged**
