### PR TITLE
Add other vityafx crates.

### PR DESCRIPTION
**Pull request by vityafx**
Adds my other crates beside the ones already existing here.

### CODE REVIEW

**Comment by vityafx** [comment]
I am actually in favour of removing `MASQ` for now, as it is closed-source right now. Not anyone can see unless they subscribe and the developers allow them to see the code, this isn't open source. Once they move back to publicly available repositories, we could revert the changes back.

**Comment by palfrey** [comment]
> I am actually in favour of removing `MASQ` for now, as it is closed-source right now. Not anyone can see unless they subscribe and the developers allow them to see the code, this isn't open source. Once they move back to publicly available repositories, we could revert the changes back.
> 
> UPD I noticed the awesome rust isn't just about open source projects, but it always expects links to the projects. When I removed the link to the project, the rust validator failed to validate the sorting order, so I placed their website instead of their repository link (which isn't available publicly anymore, and so the validator would fail again).

It was open source when we added it (see https://github.com/rust-unofficial/awesome-rust/pull/1085) and I've removed it in https://github.com/rust-unofficial/awesome-rust/commit/e67c5cbae35fc88d8be59997deb51530ec498430 until their github org comes back, which is reportedly due to too many people starring it in a short period of time and getting marked as spam, but either way we generally don't add closed source things.

The exception to that is "this is a thing that improves the Rust ecosystem" (e.g. Cloudsmith, because AFAIK they're practically the only commercial private crate registry out there currently), but MASQ doesn't get that without the source because they're basically just another blockchain project (which if they were rare in Rust might be something that gets them in, but they're really not!)

**Comment by palfrey** [comment]
We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).

Some of the entries here (e.g. `serde-aux`) happily pass this. Some of them (e.g. `steamidfx`) do not. Can you please either remove the ones that don't pass or point us towards other metrics we've missed?

**Comment by vityafx** [comment]
> We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).
> 
> Some of the entries here (e.g. `serde-aux`) happily pass this. Some of them (e.g. `steamidfx`) do not. Can you please either remove the ones that don't pass or point us towards other metrics we've missed?

Thanks for letting me know about the policy change.

I'll check which ones fit and which don't, remove the crates which don't, and update the PR.

**Comment by vityafx** [comment]
> We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).
> 
> Some of the entries here (e.g. `serde-aux`) happily pass this. Some of them (e.g. `steamidfx`) do not. Can you please either remove the ones that don't pass or point us towards other metrics we've missed?

Just to be sure, the condition is both, minimum of 50 stars **and** more than 2k downloads? Or either one or another or both?

**Comment by vityafx** [comment]
Okay, I guess it's both and I just misunderstood. Removing one more crate then.

**Comment by vityafx** [comment]
Well, I have just realised I have no crates with more than 50 stars as of now, so I am just closing this then.

**Comment by palfrey** [comment]
> Just to be sure, the condition is both, minimum of 50 stars **and** more than 2k downloads? Or either one or another or both?

Requirement is either! (or an equivalent elsewhere). Basically we need at least one strong signal that a project is liked by the wider community. More is good, but not required.

**Comment by vityafx** [comment]
Oh, thanks for the reply!

Okay, then, I guess, the [rust validator can't take the number of downloads](https://github.com/rust-unofficial/awesome-rust/runs/3352016399) from the crates.io...
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/awesome-rust`
[2021-08-17T15:10:17Z WARN  awesome_rust] Downloading Github stars for https://github.com/vityafx/randomorg
Error: ErrorMessage { msg: "Not good enough (3 stars < 50, and 0 cargo downloads < 2000): vityafx/randomorg - A https://www.random.org/ client library." }
Error: Process completed with exit code 1.
```

**Comment by palfrey** [comment]
I'll add a comment to the error message about this, but when it says "0" for one of the values it sometimes means that it had no data for that eg of there's no crates link in the entry as is the case for the random org one.

**Comment by vityafx** [comment]
> I'll add a comment to the error message about this, but when it says "0" for one of the values it sometimes means that it had no data for that eg of there's no crates link in the entry as is the case for the random org one.

I thought this was the case, thanks. I'll add those and then will retrigger the build.

**Comment by palfrey** [comment]
> I thought this was the case, thanks. I'll add those and then will retrigger the build.

How's this going?

**Comment by vityafx** [comment]
Finished one-by-one. Sorry for the delay.

**Comment by palfrey** [comment]
> Finished one-by-one. Sorry for the delay.

No worries. We all have lives outside of this repository :)

**Comment by vityafx** [comment]
> > Finished one-by-one. Sorry for the delay.
> 
> No worries. We all have lives outside of this repository :)

Yes, thanks :) Have a nice day there :-)

**Pull request merged**
