### PR TITLE
add sitkevij/hex under System Tools

### PR DESCRIPTION
**Pull request by sitkevij**

### CODE REVIEW

**Comment by luciusmagn** [comment]
I restarted it. You are correct that there was something wrong with Travis.
It usually doesn't stall for 12 minutes. However, just by looking at your
diff, I can tell that your changes are fine, so I will merge once the build
is over

2018-04-30 21:47 GMT+02:00 Julian Sitkevich <notifications@github.com>:

**Comment by luciusmagn** [comment]
The travis build confirmed that your entry is correct (it appears there are some warts in other places I will need to fix, though, heh). Thank you for your contribution!

**Comment by sitkevij** [comment]
Hi @luciusmagn - Thank you for working this through. However, I'm not seeing my pull request - https://github.com/rust-unofficial/awesome-rust/pull/457/files show up in master - https://github.com/rust-unofficial/awesome-rust/blob/master/README.md

Maybe my changes were overwritten by another change?

**Comment by luciusmagn** [comment]
Fixed in 15d940426f2025de27b4b1b33dc2a2e73ae02fd4 . Apologies!

**Pull request merged**
