### PR TITLE
Fix GitHub build

### PR DESCRIPTION
**Pull request by palfrey**
This PR does a couple of things, resulting in a working Github Actions build
* It upgrades a bunch of packages, mostly to solve the `error reading DNS system conf: Error parsing resolv.conf` error that was occurring on earlier Github actions builds
* It fixes all the current bad urls in README.md
* It adds lots of caching to the Github actions build, including some fun with `always-upload-cache` and `RANDOM` so that if we manage to get some items for the results cache, but it then borks later on, we a) still store the ones we managed to get and b) if we re-run the build, can repeatedly re-store the result file and incrementally get towards a working build. I did this with this one to get a green build, and may well be needed when this gets merged.

To clarify, this isn't me intending on coming back to maintaining and managing things (at least not yet), but I saw the issues here, and wanted to at least try and sort them out. Longer-term I might be able to spend some more time back here again, but we'll have to wait and see on that.

### CODE REVIEW

**Comment by luciusmagn** [comment]
Thanks, I will check this out ASAP

**Comment by palfrey** [comment]
> Thanks, I will check this out ASAP

How's this going?

**Comment by replicadse** [comment]
From what I can tell, this change looks great. The caching is also quite interesting. Builds have been broken for quite a while and the work on the bad URLs is awesome.

**Comment by palfrey** [comment]
@luciusmagn As this looks like it's a definite improvement over the current situation, unless you've got any issues with it over the next 48 hours I'm going to merge it.

**Comment by luciusmagn** [comment]
Sorry, I was a bit busy, but I am no longer.

I have taken a look and it looks very good, so I'm going to expedite the process, haha

**Pull request merged**
