### PR TITLE
Add YeeCo yeeroot to Cryptocurrencies

### PR DESCRIPTION
**Pull request by guoxbin**
YeeCo yeeroot is a permissionless, secure, high performance and scalable public blockchain platform powered by full sharding technology on PoW consensus written in Rust

### CODE REVIEW

**Comment by luciusmagn** [comment]
An interesting project indeed! Thank you for your contribution to the list!

**Comment by guoxbin** [comment]
> An interesting project indeed! Thank you for your contribution to the list!

I have merged the conflicts and hope you approve my pull request.

**Comment by guoxbin** [comment]
> An interesting project indeed! Thank you for your contribution to the list!

Would you please have a look at my pull request?

**Comment by guoxbin** [comment]
> An interesting project indeed! Thank you for your contribution to the list!

Any response to my pull request?

**Comment by luciusmagn** [comment]
Oops, I thought I had merged it, sorry sorry T-T

**Pull request merged**
