### PR TITLE
Update README.md: Add Pier as productivity tool

### PR DESCRIPTION
**Pull request by BenSchZA**

### CODE REVIEW

**Comment by BenSchZA** [comment]
Made a number of fixes to broken links.

**Comment by BenSchZA** [comment]
@luciusmagn Are you a reviewer for this repo/able to merge PR? :)

**Comment by luciusmagn** [comment]
Yes, sorry. Our current policy is to not really remove any projects from the list. Both module_linker and deps.rs can be found on Github, so the proper procedure is to replace the broken links with links to repos.

Otherwise, the PR is good and I will be able to merge it

**Comment by BenSchZA** [comment]
No problem @luciusmagn, updated the links to point at GitHub, for module_linker and deps.rs.

**Comment by luciusmagn** [comment]
Thank you, this is just what the doctor ordered!

**Pull request merged**
