### PR TITLE
Added 3 new podcasts

### PR DESCRIPTION
**Pull request by talonx**
Added 3 podcasts to the Podcast list.

### CODE REVIEW

**Comment by talonx** [comment]
Based on the build error I am guessing the problem was an unsorted list of podcasts. Hoping this last commit should fix it.

**Comment by palfrey** [comment]
Have you got any publicly available popularity metrics for any of those podcasts? We didn't necessarily have this for any of the others in the past, but trying to be stricter about this now. If these were Github repos it'd be easier, but not sure what you can provide for podcasts.

**Comment by talonx** [comment]
> Have you got any publicly available popularity metrics for any of those podcasts? We didn't necessarily have this for any of the others in the past, but trying to be stricter about this now. If these were Github repos it'd be easier, but not sure what you can provide for podcasts.

All I could find are Spotify follower numbers plus Castbox subscribers for RustShip -
- https://open.spotify.com/show/6PVQBdYnLaECFjwdpH4PgB
- https://open.spotify.com/show/0Hf6gWrzpSzXp1X0cebbsT
- https://open.spotify.com/show/3tLnLLWcvJyYTwMSi67zEA
- https://castbox.fm/channel/id5535460?country=us

Most of these podcasts are distributed via many channels, and there does not seem to be any central source which aggregates subscriber data.

**Comment by palfrey** [comment]
> > Have you got any publicly available popularity metrics for any of those podcasts? We didn't necessarily have this for any of the others in the past, but trying to be stricter about this now. If these were Github repos it'd be easier, but not sure what you can provide for podcasts.
> 
> All I could find are Spotify follower numbers plus Castbox subscribers for RustShip -
> 
>     * https://open.spotify.com/show/6PVQBdYnLaECFjwdpH4PgB
>     * https://open.spotify.com/show/0Hf6gWrzpSzXp1X0cebbsT
>     * https://open.spotify.com/show/3tLnLLWcvJyYTwMSi67zEA
> 
>     * https://castbox.fm/channel/id5535460?country=us

> Most of these podcasts are distributed via many channels, and there does not seem to be any central source which aggregates subscriber data.

I'm not seeing any Spotify numbers there, but I don't have an account there. The Castbox numbers are a lot lower than I'd hoped for to feel equivalent to the "50 Github stars" I'm comparing to. Don't need a central source (although it's useful!) but do need at least something with decent numbers.

**Comment by talonx** [comment]
> > > Have you got any publicly available popularity metrics for any of those podcasts? We didn't necessarily have this for any of the others in the past, but trying to be stricter about this now. If these were Github repos it'd be easier, but not sure what you can provide for podcasts.
> > 
> > 
> > All I could find are Spotify follower numbers plus Castbox subscribers for RustShip -
> > ```
> > * https://open.spotify.com/show/6PVQBdYnLaECFjwdpH4PgB
> > * https://open.spotify.com/show/0Hf6gWrzpSzXp1X0cebbsT
> > * https://open.spotify.com/show/3tLnLLWcvJyYTwMSi67zEA
> > 
> > * https://castbox.fm/channel/id5535460?country=us
> > ```
> 
> > Most of these podcasts are distributed via many channels, and there does not seem to be any central source which aggregates subscriber data.
> 
> I'm not seeing any Spotify numbers there, but I don't have an account there. The Castbox numbers are a lot lower than I'd hoped for to feel equivalent to the "50 Github stars" I'm comparing to. Don't need a central source (although it's useful!) but do need at least something with decent numbers.
The Spotify numbers ("stars") are below the "About" box in the podcast.

Well the issue here is different people subscribe to podcasts using different apps (Spotify, RSS feeds, Castbox etc) so it's highly unlikely there will be a single place to get such numbers.

**Comment by palfrey** [comment]
> The Spotify numbers ("stars") are below the "About" box in the podcast.

Ok. So I'm seeing 11, 8 and 3 on Spotify and 10 subscribers on Castbox. These are below the numbers I'd want for some level of parity with the repo requirements, and so I'm going to close this PR. If you're able to find subscriber numbers elsewhere (or several sources totalling to this for something) in the 50+ range (i.e same as our Github stars requirements), then please reopen. Or a play count in the 2000+ (i.e. same as our Crate download requirement).

**Pull request closed without merging**
