### PR TITLE
Add ox editor

### PR DESCRIPTION
**Pull request by spikecodes**
- [x] I have read the contributing guidelines.

I think listing [Ox](https://github.com/curlpipe/ox) (2k+ stars) as a Rust text editor would be a good addition.

### CODE REVIEW

**Comment by luciusmagn** [comment]
@spikecodes Hi, can you open the PR for editing by maintainers or merge master? Thank you and very sorry for the delay

**Comment by spikecodes** [comment]
For some reason, I don't see the checkbox to enable that
image

**Comment by luciusmagn** [comment]
Oh! I see the problem, you deleted the fork/branch you were making the PR from, so now this is only a disembodied commit pull request and as such, there is place to commit to.

I will see what I can do, I think I have two more cases of this happening - maybe I will do a manual merge with cli

**Comment by spikecodes** [comment]
Oh no! Should I open a new PR for it?

**Comment by spikecodes** [comment]
Continued here: #1022.

**Pull request closed without merging**
