### PR TITLE
Add `tdlib-rs` library to "Social networks" section

### PR DESCRIPTION
**Pull request by FedericoBruzzone**

### CODE REVIEW

**Comment by palfrey** [comment]
Repo fails on the star criteria (<50) but the crate has enough downloads to qualify. Can you add a link to that to the entry please?

**Comment by FedericoBruzzone** [comment]
Perfect, do you want me to add the shader?

**Comment by palfrey** [comment]
> Perfect, do you want me to add the shader?

Shader?

**Comment by FedericoBruzzone** [comment]
Sorry, shield -> [Latest version](https://crates.io/crates/tdlib_rs)

**Comment by palfrey** [comment]
No. See the pattern for crate links on other entries plus what https://github.com/rust-unofficial/awesome-rust/blob/main/CONTRIBUTING.md says

**Comment by FedericoBruzzone** [comment]
Let me know, it should be correct

**Pull request merged**
