### PR TITLE
Games: Remove discontinued zoc

### PR DESCRIPTION
**Pull request by trivikr**
Details: https://github.com/ozkriff/zoc

### CODE REVIEW

**Comment by luciusmagn** [comment]
Sorry, our current policy is not to remove projects unless they are outright broken or pronounced deprecated by another project by its author. Thank you for your effort though and I am looking forward for anything else you might bring forth.

@ozkriff don't be sad my dude :D

**Comment by trivikr** [comment]
> our current policy is not to remove projects unless they are outright broken or pronounced deprecated by another project by its author

@luciusmagn zoc is pronounced deprecated by it's author.
Deprecation info https://github.com/ozkriff/zoc#the-project-is-discontinued

**Comment by ozkriff** [comment]
"Discontinued", not deprecated. And I'm updating the game to keep it compiling on newer rust versions. Why do you want it to be removed?

**Comment by trivikr** [comment]
> Why do you want it to be removed?

I'd created this PR when I was going through the awesome-rust list back in October - nothing for/against any particular project.

The maintainers can choose to keep unbroken or discontinued but not deprecated projects in the awesome-rust list.

**Pull request closed without merging**
