### PR TITLE
Add time crate

### PR DESCRIPTION
**Pull request by jhpratt**

### CODE REVIEW

**Comment by luciusmagn** [comment]
@jhpratt Hello, can you please allow editing from maintainers or alternatively merge master branch? Thank you and sorry for the delay.

**Comment by jhpratt** [comment]
Due to the delay, I already to have already deleted the fork. Feel free to use that line directly. If you'd prefer, I can resubmit this PR while up-to-date when I get time.

**Comment by luciusmagn** [comment]
Ah, alright, I see. Thank you for your fast reply and I am sorry for the inconvenience, I'll see to it that the project is added!

**Comment by luciusmagn** [comment]
Alright, this should be resolved by #1019 

Thank you for your contribution to the list!

**Pull request closed without merging**
