### PR TITLE
youki - Container runtime written in Rust

### PR DESCRIPTION
**Pull request by utam0k**
[containers/youki](https://github.com/containers/youki)

### CODE REVIEW

**Comment by utam0k** [comment]
@palfrey Is this PR the reason why CI is failed?

**Comment by palfrey** [comment]
@utam0k I don't think so. There are a variety of other issues, which I'm trying to avoid being the one resolving, mostly because of the stuff in https://github.com/rust-unofficial/awesome-rust/issues/981

Basically, this project really needs someone with a lot of time on their hands to fix a lot of things, and then be able to continue to review things ongoing (maybe with the help of automated tools to reduce it), and that's not really me as I'm _mostly_ not motivated towards fixing stuff here (barring occasional bursts when my irritation at things being broken exceeds my lack of motivation otherwise)

**Comment by utam0k** [comment]
@palfrey I see. I understand. I'll wait for it to be reviewed. Thank you for your reply.

**Comment by utam0k** [comment]
@palfrey I see. I understand. I'll wait for it to be reviewed. Thank you for your reply.

**Comment by utam0k** [comment]
@palfrey Thank you for fixing it.

**Pull request merged**
