### PR TITLE
feat: add async-dropper to asynchronous libs

### PR DESCRIPTION
**Pull request by t3hmrman**
Thanks for the awesome listing! I added my project `async-dropper` which is for people who want an `AsyncDrop` -- it has two implementations (one derive macro based, the other a simple wrapper object)

### CODE REVIEW

**Comment by palfrey** [comment]
See build logs for some stuff that needs correcting.

**Comment by t3hmrman** [comment]
Ahh @palfrey thanks -- looks like I have some spaces and maybe emacs chopped the newline from the end of the file, will fix

**Comment by t3hmrman** [comment]
Should be fixed, and rebased to master now

**Comment by palfrey** [comment]
Sort order also needs fixing. See logs.

**Comment by t3hmrman** [comment]
Thanks for the corrections!

**Pull request merged**
