### PR TITLE
spellcheck

### PR DESCRIPTION
**Pull request by giripriyadarshan**
changed 2 spelling mistakes .... there might be more, but only these 2 caught my eyes

### CODE REVIEW

**Comment by palfrey** [comment]
Thank you. There's some conflicts now though. If you can resolve them, I'll merge this.

**Comment by giripriyadarshan** [comment]
thank you ..... resolved the conflicts

**Comment by palfrey** [comment]
Not seeing any changes now?

**Comment by giripriyadarshan** [comment]
nope ...

**Pull request closed without merging**
