### PR TITLE
Request to add a lightweight and distributed task scheduling platform to the readme.

### PR DESCRIPTION
**Pull request by BinChengZhao**
Request to add a lightweight and distributed task scheduling platform to the readme.
full name is  [delicate](https://github.com/BinChengZhao/delicate).

### CODE REVIEW

**Comment by palfrey** [comment]
This doesn't really need a new section. It can go under the existing "task scheduling" bit at https://github.com/rust-unofficial/awesome-rust#task-scheduling. Can you move it please?

**Comment by BinChengZhao** [comment]
> https://github.com/rust-unofficial/awesome-rust#task-scheduling



> This doesn't really need a new section. It can go under the existing "task scheduling" bit at https://github.com/rust-unofficial/awesome-rust#task-scheduling. Can you move it please?

Thanks for the heads up, I was thinking the same thing as you at first.

But `#task-scheduling` is under the **Libraries** module, and the `delicate` project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries**-`#task-scheduling` category~

I think it would be better to open a new entry without affecting the existing categories.

**Comment by BinChengZhao** [comment]
> > https://github.com/rust-unofficial/awesome-rust#task-scheduling
> 
> > This doesn't really need a new section. It can go under the existing "task scheduling" bit at https://github.com/rust-unofficial/awesome-rust#task-scheduling. Can you move it please?
> 
> Thanks for the heads up, I was thinking the same thing as you at first.
> 
> But `#task-scheduling` is under the **Libraries** module, and the `delicate` project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries**-`#task-scheduling` category~
> 
> I think it would be better to open a new entry without affecting the existing categories.

@

**Comment by BinChengZhao** [comment]
> > https://github.com/rust-unofficial/awesome-rust#task-scheduling
> 
> > This doesn't really need a new section. It can go under the existing "task scheduling" bit at https://github.com/rust-unofficial/awesome-rust#task-scheduling. Can you move it please?
> 
> Thanks for the heads up, I was thinking the same thing as you at first.
> 
> But `#task-scheduling` is under the **Libraries** module, and the `delicate` project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries**-`#task-scheduling` category~
> 
> I think it would be better to open a new entry without affecting the existing categories.



> > https://github.com/rust-unofficial/awesome-rust#task-scheduling
> 
> > This doesn't really need a new section. It can go under the existing "task scheduling" bit at https://github.com/rust-unofficial/awesome-rust#task-scheduling. Can you move it please?
> 
> Thanks for the heads up, I was thinking the same thing as you at first.
> 
> But `#task-scheduling` is under the **Libraries** module, and the `delicate` project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries**-`#task-scheduling` category~
> 
> I think it would be better to open a new entry without affecting the existing categories.

**Comment by BinChengZhao** [comment]
Hi  @palfrey :

Thanks for the heads up, I was thinking the same thing as you at first.

But #task-scheduling is under the **Libraries** module, and the delicate project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries-#task-scheduling** category~

I think it would be better to open a new entry without affecting the existing categories.

I look forward to your reply.

**Comment by palfrey** [comment]
> But #task-scheduling is under the **Libraries** module, and the delicate project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries-#task-scheduling** category~
> 
> I think it would be better to open a new entry without affecting the existing categories.

So, "distributed platform" is a little bit vague, and so we should have something more specific as a category title. I agree now with not putting it under the Libraries area, but "Task Scheduling" is probably still a good description of this. Can you please add a section under "Applications" called that for this please!

**Comment by BinChengZhao** [comment]
> > But #task-scheduling is under the **Libraries** module, and the delicate project is an application and a platform, so it seems a bit inappropriate to put it under the **Libraries-#task-scheduling** category~
> > I think it would be better to open a new entry without affecting the existing categories.
> 
> So, "distributed platform" is a little bit vague, and so we should have something more specific as a category title. I agree now with not putting it under the Libraries area, but "Task Scheduling" is probably still a good description of this. Can you please add a section under "Applications" called that for this please!

Sure, thanks a lot for the advice!
Now that's corrected!

**Pull request merged**
