### PR TITLE
add so_stupid_search tool to text processing section

### PR DESCRIPTION
**Pull request by Lispre**
sss(so_stupid_search) is a tiny and fast string search tool for Texter(eg: programmer)

### CODE REVIEW

**Comment by ngirard** [comment]
I'm afraid I'd have to disagree. Proposed tool has no interest over existing tools (e.g. ripgrep), besides fulfilling the author's self-educational needs.

**Comment by Lispre** [comment]
> I'm afraid I'd have to disagree. Proposed tool has no interest over existing tools (e.g. ripgrep), besides fulfilling the author's self-educational needs.

I really can not agree with you

**Comment by Shaddy** [comment]
I'm with @ngirard, awesome-rust is a curated list. What is the point on having a non-efficient "file" of 230 lines that aren't even a source of inspiration?

**Comment by ngirard** [comment]
@Lispre, if you think your tool does bring something useful to the table, I'd suggest describing your project's strengths in the README file. It's unlikely you sell your tool to anyone with an empty README file.

**Comment by ngirard** [comment]
@luciusmagn, could you please elaborate on your rationale for this addition ? 

Did you notice that the sole person pushing for it is the author of the tool, and he himself was unable to justify this addition ?

**Pull request merged**
