### PR TITLE
firebase-rs crate added to README.md

### PR DESCRIPTION
**Pull request by emreyalvac**

### CODE REVIEW

**Comment by palfrey** [comment]
Just tried `cargo test` for this library, and a whole bunch of doc tests failed, which is rather concerning.

**Comment by emreyalvac** [comment]
@palfrey My fault. I'm fixing now :)

**Comment by palfrey** [comment]
If you were able to add some form of CI to it, that would be good as well!

**Comment by palfrey** [comment]
Closing this PR for the moment while I wait for the tests on firebase-rs to be working, and preferably also CI added. Please reopen when this is fixed.

**Pull request closed without merging**
