### PR TITLE
Add MetaCall to scripting section

### PR DESCRIPTION
**Pull request by viferga**

### CODE REVIEW

**Comment by palfrey** [comment]
I'm not seeing any link to Rust here?

**Comment by viferga** [comment]
Hi @palfrey , I added this section:
* [metacall/core](https://github.com/metacall/core) [[metacall](https://crates.io/crates/metacall)] — Cross-platform Polyglot Runtime which supports NodeJS, JavaScript, TypeScript, Python, Ruby, C#, Wasm, Java, Cobol and more. [build badge](https://gitlab.com/metacall/core)

You can see the package here in Crates: https://crates.io/crates/metacall
The code inside the Core repository can be found here: https://github.com/metacall/core/tree/develop/source/ports/rs_port

It is a polyglot so it has multiple languages, but rust is supported as you can see in the crate.

**Comment by palfrey** [comment]
Can you please fix the conflicts with the current README? It's probably because we've now fixed the alphabetical ordering issues

**Comment by palfrey** [comment]
Closing while we await fixes for the conflicts. Please re-open when fixed.

**Comment by viferga** [comment]
Hi @palfrey , sorry for being late, here's a new PR with the proper alphabetical order: https://github.com/rust-unofficial/awesome-rust/pull/1147

**Pull request closed without merging**
