### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by jinxdash**
Prettier is an opinionated code formatter https://prettier.io/

- Added `Formatters` category
  - Added [`Prettier Rust`](https://github.com/jinxdash/prettier-plugin-rust)
  - Moved `rustfmt`, `dprint`
  - Changed `rustfmt` description `+= " maintained by the Rust team and included in cargo"`
- Added [`Prettier - Code formatter (Rust)`](https://marketplace.visualstudio.com/items?itemName=jinxdash.prettier-rust) VSCode extension

### CODE REVIEW

**Comment by palfrey** [comment]
Happy with the formatter reorganisation, but all of the Prettier bits are below our thresholds for projects (50 stars on Github, 2000 downloads of a crate, or something equivalent) unless I'm missing something specific here?

**Comment by jinxdash** [comment]
Should be good now

**Comment by palfrey** [comment]
> Should be good now

It's in the wrong order. See build log
```
 [2022-08-23T10:28:24Z WARN  awesome_rust] Downloading Github stars for https://github.com/jinxdash/prettier-plugin-rust
--- original
+++ modified
@@ -1,3 +1,3 @@
 dprint — A pluggable and configurable code formatting platform build badge
-rustfmt — Rust code formatter maintained by the Rust team and included in cargo build badge
-Prettier Rust — An opinionated Rust code formatter that autofixes bad syntax (Prettier community plugin)
\ No newline at end of file
+Prettier Rust — An opinionated Rust code formatter that autofixes bad syntax (Prettier community plugin)
+rustfmt — Rust code formatter maintained by the Rust team and included in cargo build badge
\ No newline at end of file

Error: ErrorMessage { msg: "Sorting error" }
```

**Comment by palfrey** [comment]
Now https://marketplace.visualstudio.com/items?itemName=jinxdash.prettier-rust is failing the github stars/crates download limit, because it's neither a github link or a crates link :) On it's own, it also fails the download criteria as 610 < 2000, but as it's part of a project with >50 stars, it passes.

Please add an entry to the bottom of https://github.com/rust-unofficial/awesome-rust/blob/main/src/main.rs#L43 with that link and a comment noting about the project that makes it pass.

**Pull request merged**
