### PR TITLE
Add schema registry converter

### PR DESCRIPTION
**Pull request by gklijs**

### CODE REVIEW

**Comment by luciusmagn** [comment]
The URL for the travis badge should be `https://api.travis-ci.org/...` not just `https://travis-ci.org/`. Would you mind fixing the link?

**Comment by gklijs** [comment]
Sorry, my bad, it's fixed

**Comment by palfrey** [comment]
Can you also change `https://www.confluent.io/confluent-schema-registry` to `https://www.confluent.io/confluent-schema-registry/` (note the end slash) as the first one gets us a 301 to the second version. Thanks!

**Comment by gklijs** [comment]
added

**Comment by luciusmagn** [comment]
Looks good.

Thank you for your contribution to the list!

**Pull request merged**
