### PR TITLE
Add Rune and GameLisp

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by Bromeon** [comment]
Any update on this? Was also going to propose the `rune` language.

Maybe worth retrying the CI? Logs are no longer available.

**Comment by palfrey** [comment]
This has conflicts with current master README. Can you fix them please?

**Comment by schungx** [comment]
Well, I just can't see where that conflict is...  Maybe I should scrap this and the do a new PR?

**Comment by palfrey** [comment]
> Well, I just can't see where that conflict is... Maybe I should scrap this and the do a new PR?

Up to you. I'd advise just trying to merge current master into this branch and seeing what clashes as that should tell you.

**Comment by schungx** [comment]
Unfortunately I didn't keep this fork around.  I'll make a new one.

**Pull request closed without merging**
