### PR TITLE
Add Kandi link

### PR DESCRIPTION
**Pull request by kandikits**
Hello - request your review and approval on the inclusion of Explore Rust on your list.
It would be a good addition under Third Party Guides section of this article. Would you like to include it in your list? We'd love to hear your feedback.
Thanks!

### CODE REVIEW

**Comment by palfrey** [comment]
Happy with the link getting added but "Explore Rust" is way too vague. Please give a better title for the link.

**Comment by kandikits** [comment]
Thanks for your consideration. As recommended, have changed 'Explore Rust' to 'Discover Rust Libraries and Code Snippets'. Let us know if you are okay with this.

**Comment by palfrey** [comment]
It's still very vague. Mentioning your website name at least would probably help!

**Comment by kandikits** [comment]
Added the website name 'on kandi' here: * [Discover Rust Libraries & Code Snippets](https://kandi.openweaver.com/explore/rust) - A curated list of Rust libraries, authors, kits, tutorials & learning resources on kandi. Hope this helps. Thanks!

**Pull request merged**
