### PR TITLE
Couple more README fixes

### PR DESCRIPTION
**Pull request by palfrey**
Minor items, but good to fix

* rust-lua naming pointed to old name for user
* fp-core had 301'ing build badge (from #780)

### CODE REVIEW

**Comment by palfrey** [comment]
@luciusmagn Any thoughts on this, as this will fix the current build issues. Relatedly, I'd be interested in becoming a maintainer here, at least so I can fix stuff like this :)

**Comment by luciusmagn** [comment]
Thanks a lot for the fixes!

Unfortunately, I don't know who actually owns/administrates the repository at this point. A long time ago, the original author (@kud1ing) transferred the repository to `rust-unofficial` and there was a call for maintainers. I signed up alongside several other people, but all but me have since left, it appears...

**Comment by kud1ing** [comment]
Hi, i am glad that you are interested in keeping this alive.
I've left the parent organisation so that i wouldn't be tempted to spend time i don't have on this. :}
@Manishearth Can you add @palfrey as a maintainer?

**Comment by Manishearth** [comment]
Done!

**Comment by kud1ing** [comment]
Thanks.

**Comment by palfrey** [comment]
And added. Thanks!

**Comment by luciusmagn** [comment]
Awesome! The more the merrier!

**Pull request merged**
