### PR TITLE
Add a powerful live stream server project.

### PR DESCRIPTION
**Pull request by harlanc**
As subject.

### CODE REVIEW

**Comment by harlanc** [comment]
I can access the url https://api.travis-ci.com/harlanc/xiu.svg?branch=master successfully.

**Comment by palfrey** [comment]
> I can access the url https://api.travis-ci.com/harlanc/xiu.svg?branch=master successfully.

Yup. The build step is compiaining that there's a 301 from app -> api, which needs correcting to the redirect target.

**Comment by harlanc** [comment]
> > I can access the url https://api.travis-ci.com/harlanc/xiu.svg?branch=master successfully.
> 
> Yup. The build step is compiaining that there's a 301 from app -> api, which needs correcting to the redirect target.

I need confirm , does this url has problem? https://api.travis-ci.com/harlanc/xiu.svg?branch=master? But I copied it from the travis website..

image

**Comment by harlanc** [comment]
> > I can access the url https://api.travis-ci.com/harlanc/xiu.svg?branch=master successfully.
> 
> Yup. The build step is compiaining that there's a 301 from app -> api, which needs correcting to the redirect target.

It's fixed..

**Pull request merged**
