### PR TITLE
Adding quick-skeleton

### PR DESCRIPTION
**Pull request by arthrp**
Haven't found any criteria to meet to be included in the list, so will try with my small project. I was searching for a scaffolding tool, but found only few ones, which were not so easy to use (in my opinion). So I decided to make my own. It's roughly the same as Yeoman, but simpler. It doesn't have any generators, instead it uses templates (Handlebars) that are filled with user input.

### CODE REVIEW

**Comment by kud1ing** [comment]
Thank you. Would you mind moving it above "yaa110/rubigo"?

**Comment by kud1ing** [comment]
I reorder it myself.

**Comment by arthrp** [comment]
Sorry, was away for a few days. Thank you for reordering!

**Comment by kud1ing** [comment]
NP. Thanks for the addition.

**Pull request merged**
